ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ com.example.MainKt.module ]
    }
}

app {
    env = "local"
    env = ${?APP_ENV}
}

database {
    url = ""
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = ""
    password = ${?DB_PASSWORD}
    poolSize = 10
    poolSize = ${?DB_POOL_SIZE}
}

ugs {
    projectId = ""
    projectId = ${?UGS_PROJECT_ID}
    issuer = "https://player-auth.services.api.unity.com"
    issuer = ${?UGS_ISSUER}
    jwksUrl = "https://player-auth.services.api.unity.com/.well-known/jwks.json"
    jwksUrl = ${?UGS_JWKS_URL}
}
